#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.

curl https://raw.githubusercontent.com/kfox1111/testbuildl1/master/version

git clone https://github.com/kfox1111/hubbuildtools

echo "Build hook running"
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
-t $IMAGE_NAME .

hubbuildtools/fingerprint.sh $IMAGE_NAME
