#!/bin/bash
set -e

# Fails if already uploaded to prevent a new version of the same contents
# from landing.
hubbuildtools/hubcompare.sh "$DOCKER_REPO" latest "$IMAGE_NAME"

TAG=$(hubbuildtools/fetchlocalrevision.sh "$IMAGE_NAME")

docker tag "$IMAGE_NAME" "$DOCKER_REPO:$TAG"
docker push "$DOCKER_REPO:$TAG"

